
#DataSource Properties

spring:
      datasource:        url: jdbc:mysql://localhost:3306/spring_data_jpa_practise
        username: root
        password: root
        
#ORM JPA Properties      jpa:
          database-platform: org.hibernate.dialect.MySQL8Dialect          show-sql: true
          hibernate:                   ddl-auto: create                                                 
              